import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
// import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
// import Providers from "@/redux/Providers";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
const ReduxProvider = dynamic(() => import("@/redux/Providers"), {
  ssr: false,
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <div className=" md:px-20">{children}</div> */}
          <Toaster />
          <EdgeStoreProvider>
            <ReduxProvider>{children}</ReduxProvider>
          </EdgeStoreProvider>

          {/* {children} */}
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
