import type { Metadata } from "next";
import { Inter, Outfit, Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
import { QueryClient } from "@tanstack/react-query";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";
import dynamic from "next/dynamic";
import { MantineProvider } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const queryClient = new QueryClient();
const ReduxProvider = dynamic(() => import("@/redux/Providers"), {
  ssr: false,
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster />
          <EdgeStoreProvider>
            <ReduxProvider>{children}</ReduxProvider>
          </EdgeStoreProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
